src/Entity/Program.php
<?php

namespace App\Entity;

use App\Repository\ProgramRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;



/**
 * @ORM\Entity(repositoryClass=ProgramRepository::class)
 * @UniqueEntity("title")
 */
class Program
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**

     * @ORM\Column(name="title", type="string", length=255, unique=true)

     * @Assert\NotBlank()

     * @Assert\Length(max="255")

     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $summary;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $poster;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="programs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="integer")
     */
    private $year;

    /**
     * @ORM\OneToMany(targetEntity=Season::class, mappedBy="program")
     */
    private $seasons;

    /**
     * @ORM\ManyToMany(targetEntity=Actor::class, mappedBy="programs")
     */
    private $actors;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->actors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getCategoryId(): ?Category
    {
        return $this->category_id;
    }

    public function setCategoryId(?Category $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    /**
     * @return Collection|Season[]
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons[] = $season;
            $season->setProgram($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->removeElement($season)) {
            // set the owning side to null (unless already changed)
            if ($season->getProgram() === $this) {
                $season->setProgram(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Actor[]
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors[] = $actor;
            $actor->addProgram($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        if ($this->actors->removeElement($actor)) {
            $actor->removeProgram($this);
        }

        return $this;
    }

}

src/Form/ProgramType.php
<?php

namespace App\Form;

use App\Entity\Program;
use App\Entity\Actor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ProgramType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',TextType::class)
            ->add('summary',TextType::class)
            ->add('poster',TextareaType::class)
            ->add('country')
            ->add('year')
            ->add('category_id', null, ['choice_label' => 'name'])
            ->add('actors', EntityType::class, [
                'class' => Actor::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
                'by_reference' => false,]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Program::class,
        ]);
    }
}

src/Controller/ProgramController.php
<?php
// src/Controller/DefaultController.php
namespace App\Controller;

use App\Entity\Episode;
use App\Entity\Program;
use App\Entity\Season;
use App\Form\ProgramType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/program", name="program_")
 */
class ProgramController extends AbstractController
    {
    /**
     * @Route("/new", name="new")
     */

    public function new(Request $request) : Response

    {
        $program = new Program();

        $form = $this->createForm(ProgramType::class, $program);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($program);

            $entityManager->flush();

            return $this->redirectToRoute('program_index');

        }

        return $this->render('program/new.html.twig', ["form" => $form->createView()]);

    }
        /**
         * @Route ("/{id<^[0-9]+$>}", name="show")
         * @return Response
         */
        public function show(Program $program): Response
        {

            $seasons = $this->getDoctrine()->getRepository(Season::class)->findBy(['program' => $program]);

            if (!$program) {
                throw $this->createNotFoundException(
                    'No program with id : ' . $program . ' found in program\'s table.'
                );
            }
            return $this->render('program/show.html.twig', [
                'program' => $program,
                'seasons' => $seasons,
            ]);
        }

         /**
        * @Route ("/{programId}/seasons/{seasonId}", name="season_show")
        * @ParamConverter ("program", class="App\Entity\Program", options={"mapping": {"programId": "id"}})
        * @ParamConverter("season", class="App\Entity\Season", options={"mapping": {"seasonId": "id"}})
        * @return Response
        */
        public function showSeason(Program $program, Season $season) : Response
        {
            $episodes = $this->getDoctrine()
                ->getRepository(Episode::class)
                ->findBy(['season' => $season]);

            return $this->render('/program/season_show.html.twig',
                ['program' => $program, 'season' => $season, 'episodes' => $episodes]);
        }

        /**
        * @Route ("/{programId}/seasons/{seasonId}/episodes/{episodeId}", name="episode_show")
        * @ParamConverter ("program", class="App\Entity\Program", options={"mapping": {"programId": "id"}})
        * @ParamConverter("season", class="App\Entity\Season", options={"mapping": {"seasonId": "id"}})
        * @ParamConverter ("episode", class="App\Entity\Episode", options={"mapping": {"episodeId": "id"}})
        * @return Response
        */
        public function showEpisode(Program $program, Season $season, Episode $episode) :Response
        {
            return $this->render('/program/episode_show.html.twig',
                ['program' => $program, 'season' => $season, 'episode' => $episode]);
        }

        /**
        * Show all rows from Program’s entity
        *
        * @Route("/", name="index")
        * @return Response A response instance
        */
    public function index() : Response
    {
        $programs = $this->getDoctrine()
            ->getRepository(Program::class)
            ->findAll();
        return $this->render('program/index.html.twig',
            ['programs'  => $programs]);
    }
    }

templates/program/_delete_form.html.twig
<form method="post" action="{{ path('season_delete', {'id': season.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ season.id) }}">
    <button class="btn">Delete</button>
</form>

templates/program/episode_show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="media">
        <img class="align-self-start mr-3" src="{{program.poster}}" alt="{{ program.title }} poster">
        <div class="media-body">
            <h1> {{ program.title }} : Saison {{ season.number }}</h1>
            <p>({{ season.year }})</p><br>

            <h2> Episode {{ episode.number }} : {{ episode.title }}</h2>
            <h3> Synopsis </h3>
            <p>{{ episode.synopsis }}</p><br>

            <br>
            <div>
                <a href={{ path('program_season_show', { programId: program.id, seasonId: season.id }) }}>Retour à la page saisons</a>
            </div>
        </div>
    </div>



{% endblock %}

templates/program/index.html.twig
{% extends 'base.html.twig'%}

{% block title %}All programs{% endblock %}

{% block body %}
    <h1>Toutes les séries de la table program : </h1>
    {% for program in programs %}
        <div>
            <h2>{{ loop.index }} / {{ program.title }} - Catégorie : {{ program.categoryId.name }}</h2>
            <p>{{ program.summary }}</p>
            <a href="{{ path("program_show", { id: program.id }) }}">Voir la fiche</a>
        </div>
    {% else %}
        Aucune série trouvée.
    {% endfor %}

    <a href="{{ path('app_index') }}">
        Retour à l'accueil
    </a>
{% endblock %}

templates/program/new.html.twig
{% extends "base.html.twig" %}


{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type='submit' value='Add program'>
    {{ form_end(form) }}
{% endblock %}

templates/program/season_show.html.twig
{% extends 'base.html.twig'%}

{% block title %}{{ program.title }} SAISON {{ season.number }} {% endblock %}

{% block body  %}
    <div class="media">
    <img class="align-self-start mr-3" src="{{program.poster}}" alt="{{ program.title }} poster">
    <div class="media-body">
    <h1 class="mt-0">{{ program.title }} | SAISON : {{ season.number }}</h1>
        <ul>
            {% for episode in episodes %}
        <li>
            <a href="{{ path('program_episode_show', {episodeId: episode.id, programId: program.id,seasonId: season.id}) }}">Episode {{ episode.number }} : {{ episode.title }}</a>
        </li>
            {% endfor %}
    </ul>
    </div>
    </div>
    <a href="{{ path('program_show',{id: program.id}) }}">
        Retour à la liste des saisons
    </a>


{% endblock %}

templates/program/serie.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Hello ceci est la série numéro {{ id }}!</h1>
{% endblock %}

templates/program/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Série #{{ program.id }}{% endblock %}

{% block body %}
    <div class="media">
        <img class="align-self-start mr-3" src="{{program.poster}}" alt="{{ program.title }} poster">
        <div class="media-body">
            <h1 class="mt-0">{{ program.title }}</h1>
            <p>{{ program.summary }}</p>
            <p>Catégorie : {{ program.categoryId.name }}</p>
            {% for season in seasons %}
                        <span><a href="{{ path('program_season_show', {programId: program.id, seasonId: season.id}) }}">|SAISON {{ season.id }}|</a> </span>

            {% else %}
                Aucune saison disponible
            {% endfor %}
        </div>
    </div>
    <strong>Acteurs :</strong>

    <ul>

        {% for actor in program.actors %}

            <li>{{ actor.name }} </li>

        {% else %}

            <li>Aucun acteur pour cette série</li>

        {% endfor %}

    </ul>




    <a href="{{ path('program_index') }}">
        Retour à la liste des programmes
    </a>

{% endblock %}